[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "stridefy"
version = "1.0.0"
description = "STRIDE-based target categorization"
requires-python = ">=3.12"
authors = [
    {name = "foiovituh"}
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
]

[project.scripts]
stridefy = "stridefy.cli:main"

[tool.setuptools.packages.find]
where = ["src"]